/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EasyKts.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfSaveOnay = new javax.swing.JFrame();
        jpFaceOnay = new javax.swing.JPanel();
        jlFaceOnay = new javax.swing.JLabel();
        jpKimlikOnay = new javax.swing.JPanel();
        jlKimlikOnay = new javax.swing.JLabel();
        jpBarcodeOnay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlBarcodeOkunan = new javax.swing.JLabel();
        jbSaveFinal = new javax.swing.JButton();
        jbStartOver = new javax.swing.JButton();
        jcbKaydetOnay = new javax.swing.JCheckBox();
        jfSettings = new javax.swing.JFrame();
        jpSettings1 = new javax.swing.JPanel();
        jcbKullanicidanOnayIste = new javax.swing.JCheckBox();
        jcbResetFaceOnMotion = new javax.swing.JCheckBox();
        jcbResetBarcodeOnMotion = new javax.swing.JCheckBox();
        jcbExitOnSave = new javax.swing.JCheckBox();
        jcbAutoSave = new javax.swing.JCheckBox();
        jcbUserCanChangeSettings = new javax.swing.JCheckBox();
        jcbSound = new javax.swing.JCheckBox();
        jpSettings2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jrbBarcodeFormatSimple = new javax.swing.JRadioButton();
        jrbBarcodeFormatJSON = new javax.swing.JRadioButton();
        jpSettings3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jrbModeFaceOnly = new javax.swing.JRadioButton();
        jrbModeBarcodeOnly = new javax.swing.JRadioButton();
        jrbModeBoth = new javax.swing.JRadioButton();
        jbSettingsSave = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtfSaveLocation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jbSaveLocationButton = new javax.swing.JButton();
        bgBarcodeFormat = new javax.swing.ButtonGroup();
        bgMode = new javax.swing.ButtonGroup();
        jpSelectCam = new javax.swing.JPanel();
        jcbCams = new javax.swing.JComboBox<String>();
        jbSettings = new javax.swing.JButton();
        jpMain = new javax.swing.JPanel();
        jpCamera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpFaceMainContainer = new javax.swing.JPanel();
        jpFace = new javax.swing.JPanel();
        jlFace = new javax.swing.JLabel();
        jbKimlikReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlGifFace = new javax.swing.JLabel();
        jpBarcodeContainer = new javax.swing.JPanel();
        jlBarcodeText = new javax.swing.JLabel();
        jbBarcodeReset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlGifBarcode = new javax.swing.JLabel();
        jpSaveAll = new javax.swing.JPanel();
        jbSaveAll = new javax.swing.JButton();
        jbResetAll = new javax.swing.JButton();

        jpFaceOnay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpFaceOnay.setMaximumSize(new java.awt.Dimension(110, 110));
        jpFaceOnay.setMinimumSize(new java.awt.Dimension(110, 110));

        jlFaceOnay.setMaximumSize(new java.awt.Dimension(110, 110));
        jlFaceOnay.setMinimumSize(new java.awt.Dimension(110, 110));
        jlFaceOnay.setPreferredSize(new java.awt.Dimension(110, 110));

        javax.swing.GroupLayout jpFaceOnayLayout = new javax.swing.GroupLayout(jpFaceOnay);
        jpFaceOnay.setLayout(jpFaceOnayLayout);
        jpFaceOnayLayout.setHorizontalGroup(
            jpFaceOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFaceOnay, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        jpFaceOnayLayout.setVerticalGroup(
            jpFaceOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFaceOnay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpKimlikOnay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpKimlikOnay.setMaximumSize(new java.awt.Dimension(110, 110));
        jpKimlikOnay.setMinimumSize(new java.awt.Dimension(110, 110));

        jlKimlikOnay.setMaximumSize(new java.awt.Dimension(110, 110));
        jlKimlikOnay.setMinimumSize(new java.awt.Dimension(110, 110));
        jlKimlikOnay.setPreferredSize(new java.awt.Dimension(110, 110));

        javax.swing.GroupLayout jpKimlikOnayLayout = new javax.swing.GroupLayout(jpKimlikOnay);
        jpKimlikOnay.setLayout(jpKimlikOnayLayout);
        jpKimlikOnayLayout.setHorizontalGroup(
            jpKimlikOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlKimlikOnay, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jpKimlikOnayLayout.setVerticalGroup(
            jpKimlikOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlKimlikOnay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpBarcodeOnay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("QR/Barkod Okunan");

        jlBarcodeOkunan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlBarcodeOkunan.setText("Okunamadı!");

        javax.swing.GroupLayout jpBarcodeOnayLayout = new javax.swing.GroupLayout(jpBarcodeOnay);
        jpBarcodeOnay.setLayout(jpBarcodeOnayLayout);
        jpBarcodeOnayLayout.setHorizontalGroup(
            jpBarcodeOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBarcodeOnayLayout.createSequentialGroup()
                .addGroup(jpBarcodeOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jpBarcodeOnayLayout.createSequentialGroup()
                        .addComponent(jlBarcodeOkunan, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(46, 46, 46)))
                .addContainerGap())
        );
        jpBarcodeOnayLayout.setVerticalGroup(
            jpBarcodeOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBarcodeOnayLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jlBarcodeOkunan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        jbSaveFinal.setText("ONAYLIYORUM");
        jbSaveFinal.setEnabled(false);

        jbStartOver.setText("BAŞA DÖN");

        jcbKaydetOnay.setText("Kontrol Ettim");

        javax.swing.GroupLayout jfSaveOnayLayout = new javax.swing.GroupLayout(jfSaveOnay.getContentPane());
        jfSaveOnay.getContentPane().setLayout(jfSaveOnayLayout);
        jfSaveOnayLayout.setHorizontalGroup(
            jfSaveOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSaveOnayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFaceOnay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpKimlikOnay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBarcodeOnay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jfSaveOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfSaveOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbSaveFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbStartOver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jcbKaydetOnay))
                .addContainerGap())
        );
        jfSaveOnayLayout.setVerticalGroup(
            jfSaveOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSaveOnayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jfSaveOnayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfSaveOnayLayout.createSequentialGroup()
                        .addComponent(jcbKaydetOnay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSaveFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbStartOver))
                    .addComponent(jpKimlikOnay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpFaceOnay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBarcodeOnay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpSettings1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcbKullanicidanOnayIste.setText("Kaydederken kullanıcıdan doğrulama iste");

        jcbResetFaceOnMotion.setText("Hareket halinde bulunan yüzü sıfırla");

        jcbResetBarcodeOnMotion.setText("Hareket halinde bulunan barkodu sıfırla");

        jcbExitOnSave.setText("Kaydetme sonrası çıkış yap");

        jcbAutoSave.setText("Otomatik kaydet");

        jcbUserCanChangeSettings.setText("Ayarlara sonradan erişim");

        jcbSound.setSelected(true);
        jcbSound.setText("Sonuç bulduğunda ses çıkart");

        javax.swing.GroupLayout jpSettings1Layout = new javax.swing.GroupLayout(jpSettings1);
        jpSettings1.setLayout(jpSettings1Layout);
        jpSettings1Layout.setHorizontalGroup(
            jpSettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSettings1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbResetBarcodeOnMotion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpSettings1Layout.createSequentialGroup()
                        .addGroup(jpSettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbKullanicidanOnayIste)
                            .addComponent(jcbResetFaceOnMotion)
                            .addComponent(jcbExitOnSave)
                            .addComponent(jcbAutoSave)
                            .addComponent(jcbUserCanChangeSettings)
                            .addComponent(jcbSound))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpSettings1Layout.setVerticalGroup(
            jpSettings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSettings1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbKullanicidanOnayIste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbResetFaceOnMotion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbResetBarcodeOnMotion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbExitOnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbAutoSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbUserCanChangeSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbSound)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpSettings2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Barkodları şu formatta kaydet");

        bgBarcodeFormat.add(jrbBarcodeFormatSimple);
        jrbBarcodeFormatSimple.setSelected(true);
        jrbBarcodeFormatSimple.setText("Basit");

        bgBarcodeFormat.add(jrbBarcodeFormatJSON);
        jrbBarcodeFormatJSON.setText("JSON");

        javax.swing.GroupLayout jpSettings2Layout = new javax.swing.GroupLayout(jpSettings2);
        jpSettings2.setLayout(jpSettings2Layout);
        jpSettings2Layout.setHorizontalGroup(
            jpSettings2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSettings2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(79, 79, 79))
            .addGroup(jpSettings2Layout.createSequentialGroup()
                .addComponent(jrbBarcodeFormatSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbBarcodeFormatJSON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(129, 129, 129))
        );
        jpSettings2Layout.setVerticalGroup(
            jpSettings2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSettings2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpSettings2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbBarcodeFormatSimple)
                    .addComponent(jrbBarcodeFormatJSON))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpSettings3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Çalışma modu");

        bgMode.add(jrbModeFaceOnly);
        jrbModeFaceOnly.setText("Yanlızca Yüz");

        bgMode.add(jrbModeBarcodeOnly);
        jrbModeBarcodeOnly.setText("Yanlızca Barkod");

        bgMode.add(jrbModeBoth);
        jrbModeBoth.setSelected(true);
        jrbModeBoth.setText("Yüz ve Barkod");

        javax.swing.GroupLayout jpSettings3Layout = new javax.swing.GroupLayout(jpSettings3);
        jpSettings3.setLayout(jpSettings3Layout);
        jpSettings3Layout.setHorizontalGroup(
            jpSettings3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSettings3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpSettings3Layout.createSequentialGroup()
                .addGroup(jpSettings3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbModeFaceOnly)
                    .addComponent(jrbModeBarcodeOnly)
                    .addComponent(jrbModeBoth))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpSettings3Layout.setVerticalGroup(
            jpSettings3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSettings3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbModeFaceOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbModeBarcodeOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbModeBoth)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSettingsSave.setText("Kaydet");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtfSaveLocation.setEditable(false);

        jLabel7.setText("Kayıt yeri:");

        jbSaveLocationButton.setText("Değiştir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtfSaveLocation)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbSaveLocationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfSaveLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSaveLocationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jfSettingsLayout = new javax.swing.GroupLayout(jfSettings.getContentPane());
        jfSettings.getContentPane().setLayout(jfSettingsLayout);
        jfSettingsLayout.setHorizontalGroup(
            jfSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSettingsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jfSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSettingsSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfSettingsLayout.createSequentialGroup()
                        .addComponent(jpSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jfSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpSettings3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpSettings2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jfSettingsLayout.setVerticalGroup(
            jfSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfSettingsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jfSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpSettings1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jfSettingsLayout.createSequentialGroup()
                        .addComponent(jpSettings3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpSettings2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSettingsSave, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpSelectCam.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcbCams.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lütfen Bekleyiniz" }));

        jbSettings.setText("Ayar");

        javax.swing.GroupLayout jpSelectCamLayout = new javax.swing.GroupLayout(jpSelectCam);
        jpSelectCam.setLayout(jpSelectCamLayout);
        jpSelectCamLayout.setHorizontalGroup(
            jpSelectCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSelectCamLayout.createSequentialGroup()
                .addComponent(jcbCams, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jbSettings))
        );
        jpSelectCamLayout.setVerticalGroup(
            jpSelectCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSelectCamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jcbCams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbSettings))
        );

        jpMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpCamera.setBackground(new java.awt.Color(51, 51, 51));
        jpCamera.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Lütfen Bekleyiniz...");

        javax.swing.GroupLayout jpCameraLayout = new javax.swing.GroupLayout(jpCamera);
        jpCamera.setLayout(jpCameraLayout);
        jpCameraLayout.setHorizontalGroup(
            jpCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCameraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jpCameraLayout.setVerticalGroup(
            jpCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCameraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpFaceMainContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpFace.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpFace.setMaximumSize(new java.awt.Dimension(110, 110));
        jpFace.setMinimumSize(new java.awt.Dimension(110, 110));
        jpFace.setPreferredSize(new java.awt.Dimension(110, 110));

        jlFace.setMaximumSize(new java.awt.Dimension(110, 110));
        jlFace.setMinimumSize(new java.awt.Dimension(110, 110));
        jlFace.setPreferredSize(new java.awt.Dimension(110, 110));

        javax.swing.GroupLayout jpFaceLayout = new javax.swing.GroupLayout(jpFace);
        jpFace.setLayout(jpFaceLayout);
        jpFaceLayout.setHorizontalGroup(
            jpFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpFaceLayout.setVerticalGroup(
            jpFaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlFace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jbKimlikReset.setText("Tekrar Al");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kimlik Tanıma");

        jlGifFace.setMaximumSize(new java.awt.Dimension(25, 25));
        jlGifFace.setMinimumSize(new java.awt.Dimension(25, 25));
        jlGifFace.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout jpFaceMainContainerLayout = new javax.swing.GroupLayout(jpFaceMainContainer);
        jpFaceMainContainer.setLayout(jpFaceMainContainerLayout);
        jpFaceMainContainerLayout.setHorizontalGroup(
            jpFaceMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFaceMainContainerLayout.createSequentialGroup()
                .addGroup(jpFaceMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFaceMainContainerLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jpFace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFaceMainContainerLayout.createSequentialGroup()
                        .addComponent(jlGifFace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addComponent(jbKimlikReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpFaceMainContainerLayout.setVerticalGroup(
            jpFaceMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFaceMainContainerLayout.createSequentialGroup()
                .addGroup(jpFaceMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlGifFace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpFace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbKimlikReset)
                .addContainerGap())
        );

        jpBarcodeContainer.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlBarcodeText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlBarcodeText.setForeground(new java.awt.Color(102, 102, 102));
        jlBarcodeText.setText("...");

        jbBarcodeReset.setText("Tekrar Oku");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("QR Kod / Barkod");

        jlGifBarcode.setMaximumSize(new java.awt.Dimension(25, 25));
        jlGifBarcode.setMinimumSize(new java.awt.Dimension(25, 25));
        jlGifBarcode.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout jpBarcodeContainerLayout = new javax.swing.GroupLayout(jpBarcodeContainer);
        jpBarcodeContainer.setLayout(jpBarcodeContainerLayout);
        jpBarcodeContainerLayout.setHorizontalGroup(
            jpBarcodeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBarcodeContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpBarcodeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBarcodeReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBarcodeContainerLayout.createSequentialGroup()
                        .addGroup(jpBarcodeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBarcodeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpBarcodeContainerLayout.createSequentialGroup()
                                .addComponent(jlGifBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addContainerGap())))
        );
        jpBarcodeContainerLayout.setVerticalGroup(
            jpBarcodeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBarcodeContainerLayout.createSequentialGroup()
                .addGroup(jpBarcodeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlGifBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlBarcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBarcodeReset)
                .addContainerGap())
        );

        jpSaveAll.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbSaveAll.setText("Kaydet");

        jbResetAll.setText("Sıfırla");

        javax.swing.GroupLayout jpSaveAllLayout = new javax.swing.GroupLayout(jpSaveAll);
        jpSaveAll.setLayout(jpSaveAllLayout);
        jpSaveAllLayout.setHorizontalGroup(
            jpSaveAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbResetAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jbSaveAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpSaveAllLayout.setVerticalGroup(
            jpSaveAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSaveAllLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jbResetAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSaveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addComponent(jpCamera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpFaceMainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpBarcodeContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSaveAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCamera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMainLayout.createSequentialGroup()
                .addComponent(jpFaceMainContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpBarcodeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSaveAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpSelectCam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpSelectCam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup bgBarcodeFormat;
    public javax.swing.ButtonGroup bgMode;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbBarcodeReset;
    public javax.swing.JButton jbKimlikReset;
    public javax.swing.JButton jbResetAll;
    public javax.swing.JButton jbSaveAll;
    public javax.swing.JButton jbSaveFinal;
    public javax.swing.JButton jbSaveLocationButton;
    public javax.swing.JButton jbSettings;
    public javax.swing.JButton jbSettingsSave;
    public javax.swing.JButton jbStartOver;
    public javax.swing.JCheckBox jcbAutoSave;
    public javax.swing.JComboBox<String> jcbCams;
    public javax.swing.JCheckBox jcbExitOnSave;
    public javax.swing.JCheckBox jcbKaydetOnay;
    public javax.swing.JCheckBox jcbKullanicidanOnayIste;
    public javax.swing.JCheckBox jcbResetBarcodeOnMotion;
    public javax.swing.JCheckBox jcbResetFaceOnMotion;
    public javax.swing.JCheckBox jcbSound;
    public javax.swing.JCheckBox jcbUserCanChangeSettings;
    public javax.swing.JFrame jfSaveOnay;
    public javax.swing.JFrame jfSettings;
    public javax.swing.JLabel jlBarcodeOkunan;
    public javax.swing.JLabel jlBarcodeText;
    public javax.swing.JLabel jlFace;
    public javax.swing.JLabel jlFaceOnay;
    public javax.swing.JLabel jlGifBarcode;
    public javax.swing.JLabel jlGifFace;
    public javax.swing.JLabel jlKimlikOnay;
    public javax.swing.JPanel jpBarcodeContainer;
    public javax.swing.JPanel jpBarcodeOnay;
    public javax.swing.JPanel jpCamera;
    public javax.swing.JPanel jpFace;
    public javax.swing.JPanel jpFaceMainContainer;
    public javax.swing.JPanel jpFaceOnay;
    public javax.swing.JPanel jpKimlikOnay;
    public javax.swing.JPanel jpMain;
    public javax.swing.JPanel jpSaveAll;
    public javax.swing.JPanel jpSelectCam;
    public javax.swing.JPanel jpSettings1;
    public javax.swing.JPanel jpSettings2;
    public javax.swing.JPanel jpSettings3;
    public javax.swing.JRadioButton jrbBarcodeFormatJSON;
    public javax.swing.JRadioButton jrbBarcodeFormatSimple;
    public javax.swing.JRadioButton jrbModeBarcodeOnly;
    public javax.swing.JRadioButton jrbModeBoth;
    public javax.swing.JRadioButton jrbModeFaceOnly;
    public javax.swing.JTextField jtfSaveLocation;
    // End of variables declaration//GEN-END:variables
}
